### PR TITLE
add AndyTauber to OWNERS

### PR DESCRIPTION
**Pull request by AndyTauber**
Signed-off-by: Andrew Tauber <atauber@vmware.com>

### CODE REVIEW

**Comment by navidshaikh** [comment]
>User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.

think Andy needs to be added as collaborator first cc: @rajaskakodkar

**Comment by rajaskakodkar** [comment]
@AndyTauber I have sent you an invite to join this repo as a collaborator. Once you accept that, we'll be able to merge this PR.

**Pull request merged**
